'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const DeepDiveInputSchema = z.object({
  query: z.string().describe('The user query for a deep dive.'),
});

const DeepDiveOutputSchema = z.object({
  answer: z.string().describe('A detailed, multi-perspective answer.'),
  sources: z.array(z.object({
    url: z.string(),
    title: z.string(),
  })).describe('List of sources used.'),
  reasoning: z.string().describe('Detailed reasoning for the answer.'),
  confidenceScore: z.number().describe('Confidence score from 0 to 1.'),
});

const webSearchTool = ai.defineTool({
  name: 'webSearch',
  description: 'Search the web for general information.',
  inputSchema: z.object({ query: z.string() }),
  outputSchema: z.string(),
}, async (input) => `Mock web search results for "${input.query}".`);

const wikipediaSearchTool = ai.defineTool({
  name: 'wikipediaSearch',
  description: 'Search Wikipedia for encyclopedic information.',
  inputSchema: z.object({ query: z.string() }),
  outputSchema: z.string(),
}, async (input) => `Mock Wikipedia results for "${input.query}".`);

const arxivSearchTool = ai.defineTool({
  name: 'arxivSearch',
  description: 'Search ArXiv for academic papers.',
  inputSchema: z.object({ query: z.string() }),
  outputSchema: z.string(),
}, async (input) => `Mock ArXiv results for "${input.query}".`);


const deepDivePrompt = ai.definePrompt({
  name: 'deepDivePrompt',
  input: { schema: DeepDiveInputSchema },
  output: { schema: DeepDiveOutputSchema },
  tools: [webSearchTool, wikipediaSearchTool, arxivSearchTool],
  prompt: `You are an expert researcher. Perform a "deep dive" on the following query by synthesizing information from web search, Wikipedia, and ArXiv.
  Provide a detailed, multi-perspective answer. Be comprehensive.
  
  Query: {{{query}}}
  `,
});

export const deepDiveFlow = ai.defineFlow(
  {
    name: 'deepDiveFlow',
    inputSchema: DeepDiveInputSchema,
    outputSchema: DeepDiveOutputSchema,
  },
  async (input) => {
    const { output } = await deepDivePrompt(input);
    
    if (!output) {
      // Provide a mock response if the prompt fails
      return {
        answer: `This is a mock deep dive answer for the query: "${input.query}". A real implementation would synthesize data from multiple sources like web search, Wikipedia, and ArXiv to provide a comprehensive, multi-perspective analysis.`,
        sources: [
          { url: 'https://example.com/web', title: 'Mock Web Source' },
          { url: 'https://example.com/wiki', title: 'Mock Wikipedia Source' },
          { url: 'https://example.com/arxiv', title: 'Mock ArXiv Source' },
        ],
        reasoning: "This mock answer was generated by a placeholder flow. It demonstrates the structure of a deep dive response, which involves fusing information from various tools to create a detailed answer.",
        confidenceScore: 0.88,
      };
    }

    return output;
  }
);
