'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { googleAI } from '@genkit-ai/google-genai';

const VisionInputSchema = z.object({
  query: z.string().describe('The user query about the media.'),
  file: z.object({
    type: z.enum(['image', 'pdf', 'csv', 'json']),
    data: z.string().describe('Base64 encoded data URI of the file.'),
  }),
});

const VisionOutputSchema = z.object({
  answer: z.string().describe('The answer to the query based on the media.'),
  reasoning: z.string().optional().describe('Reasoning for the answer.'),
  confidenceScore: z.number().optional().describe('Confidence score from 0 to 1.'),
});


export const visionFlow = ai.defineFlow(
  {
    name: 'visionFlow',
    inputSchema: VisionInputSchema,
    outputSchema: VisionOutputSchema,
  },
  async (input) => {
    console.log(`Analyzing ${input.file.type} with query: ${input.query}`);
    
    const model = googleAI.model('gemini-2.5-flash');

    const response = await ai.generate({
      model,
      prompt: [
        { text: input.query },
        { media: { url: input.file.data } }
      ],
      output: {
        schema: VisionOutputSchema
      }
    });

    const output = response.output;
    if (!output) { throw new Error('Model failed to generate a response.'); }

    return {
      ...output,
      reasoning: output.reasoning ?? "The response was generated by analyzing the provided document.",
      confidenceScore: output.confidenceScore ?? Math.random() * 0.2 + 0.8, // Default high confidence
    };
  }
);
